image:
  tag: prod
ingress:
  hosts:
    - host: auth.political-sphere.example
      paths:
        - path: /
          pathType: Prefix
  tls:
    - hosts:
        - auth.political-sphere.example
      secretName: auth-prod-tls
serviceAccount:
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::123456789012:role/political-sphere-prod-auth
