apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "db-proxy.fullname" . }}-config
  labels:
    {{- include "db-proxy.labels" . | nindent 4 }}
data:
  pgbouncer.ini: |
    {{- tpl .Values.config.pgbouncer . | nindent 4 }}
  databases.ini: |
    {{- tpl .Values.config.databases . | nindent 4 }}
