apiVersion: v1
kind: Service
metadata:
  name: {{ include "db-proxy.fullname" . }}
  labels:
    {{- include "db-proxy.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: pgbouncer
      port: {{ .Values.service.port }}
      targetPort: pgbouncer
      protocol: TCP
  selector:
    {{- include "db-proxy.selectorLabels" . | nindent 4 }}
