{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "db-proxy.serviceAccountName" . }}
  labels:
    {{- include "db-proxy.labels" . | nindent 4 }}
  annotations:
    {{- range $key, $value := .Values.serviceAccount.annotations }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
{{- end }}
