apiVersion: v2
name: platform-core
version: 0.1.0
description: Core cluster services (ingress, cert-manager, external-dns, monitoring, logging, gitops) for Political Sphere.
type: application

dependencies:
  - name: ingress-nginx
    version: 4.11.1
    repository: https://kubernetes.github.io/ingress-nginx
  - name: cert-manager
    version: 1.14.4
    repository: https://charts.jetstack.io
  - name: external-dns
    version: 1.14.5
    repository: https://charts.bitnami.com/bitnami
  - name: argo-cd
    version: 5.51.6
    repository: https://argoproj.github.io/argo-helm
  - name: kube-prometheus-stack
    alias: monitoring
    version: 58.4.0
    repository: https://prometheus-community.github.io/helm-charts
  - name: loki-stack
    version: 2.10.2
    repository: https://grafana.github.io/helm-charts
  - name: tempo
    version: 1.6.2
    repository: https://grafana.github.io/helm-charts
  - name: fluent-bit
    version: 0.46.6
    repository: https://fluent.github.io/helm-charts
